# 01 Data Exploration

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../../dataset/telecom_real_measurements.csv')

In [3]:
print(df.shape)

(14020, 17)

In [4]:
display(df.head())

,operator,timestamp,latitude,longitude,download_mbps,upload_mbps,rtt_ms,network_technology,5g_frequency_mhz,5g_pci,lte_earfcn,cell_event,source_drive,source_file,rtt_source_file,source_time_stamp_seconds,rtt_timestamp
0,AT&T,2023-05-13T14:29:00+00:00,42.355137,-71.118423,1.820,0.036,62.1,NaN,NaN,NaN,700.0,NaN,d2,datasets/processed_files/extracted_tput_data/a...,datasets/processed_files/extracted_ping_data/a...,1.683988e+09,2023-05-13T14:29:00.013000+00:00
1,AT&T,2023-05-13T14:29:00.600000+00:00,42.355225,-71.118469,2.530,0.045,74.4,NaN,NaN,NaN,700.0,NaN,d2,datasets/processed_files/extracted_tput_data/a...,datasets/processed_files/extracted_ping_data/a...,1.683988e+09,2023-05-13T14:29:00.613000+00:00
2,AT&T,2023-05-13T14:29:01+00:00,42.355286,-71.118507,2.948,0.051,55.4,NaN,NaN,NaN,700.0,NaN,d2,datasets/processed_files/extracted_tput_data/a...,datasets/processed_files/extracted_ping_data/a...,1.683988e+09,2023-05-13T14:29:01.013000+00:00
3,AT&T,2023-05-13T14:29:03+00:00,42.355606,-71.118698,7.347,0.121,77.0,NaN,NaN,NaN,700.0,NaN,d2,datasets/processed_files/extracted_tput_data/a...,datasets/processed_files/extracted_ping_data/a...,1.683988e+09,2023-05-13T14:29:03.013000+00:00
4,AT&T,2023-05-13T14:29:03.600000+00:00,42.355701,-71.118767,8.253,0.138,63.3,NaN,873.85,650.0,700.0,NaN,d2,datasets/processed_files/extracted_tput_data/a...,datasets/processed_files/extracted_ping_data/a...,1.683988e+09,2023-05-13T14:29:03.613000+00:00

In [5]:
display(df.groupby('operator')[['download_mbps','upload_mbps','rtt_ms']].agg(['count','mean','median','min','max']))

         download_mbps                                    upload_mbps  \
                 count        mean  median  min       max       count
operator
AT&T              4752   41.340930  5.7195  0.0  1046.568        4752
T-Mobile          4781  141.257066  2.7010  0.0  1277.239        4781
Verizon           4487   44.129153  1.9420  0.0  2124.367        4487

                                         rtt_ms                          \
               mean median  min      max  count       mean median   min
operator
AT&T       6.847253  0.453  0.0   70.713   4752  68.403809   60.2  24.3
T-Mobile  14.854202  0.463  0.0  120.420   4781  69.670236   54.5  20.8
Verizon    9.591452  0.428  0.0  102.775   4487  64.807065   51.1  15.7


             max
operator
AT&T      1985.0
T-Mobile  1537.0
Verizon   2636.0